name: "Review Buddy AI"
description: "AI code reviewer that auto-updates PR titles, descriptions, and labels. Supports multiple AI providers."
author: "AnkanSaha"
branding:
  icon: "edit"
  color: "blue"

inputs:
  github_token:
    description: "GitHub Token with write permissions for PRs"
    required: false
    default: "${{ github.token }}"
  gemini_api_key:
    description: "Google Gemini API Key (required when adapter is 'gemini')"
    required: false
  adaptive_api_token:
    description: "API Token for OpenRouter or GitHub Models (required for non-Gemini adapters)"
    required: false
  adapter:
    description: "AI provider adapter to use ('gemini', 'openrouter', or 'github-models')"
    required: false
    default: "gemini"
  model:
    description: "Model name to use (optional - each adapter has smart defaults)"
    required: false
  pr_number:
    description: "Pull Request Number"
    required: true
    default: "${{ github.event.pull_request.number }}"
  repository:
    description: "Repository name (owner/repo)"
    required: true
    default: "${{ github.repository }}"
  tone:
    description: "Tone of the response (professional, friendly, funny, roast)"
    required: false
    default: "roast"
  language:
    description: "Language for the response"
    required: false
    default: "hinglish"

runs:
  using: "composite"
  steps:
    - name: Run Review Buddy
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        GEMINI_API_KEY: ${{ inputs.gemini_api_key }}
        ADAPTIVE_API_TOKEN: ${{ inputs.adaptive_api_token }}
        ADAPTER: ${{ inputs.adapter }}
        MODEL: ${{ inputs.model }}
        PR_NUMBER: ${{ inputs.pr_number }}
        GITHUB_REPOSITORY: ${{ inputs.repository }}
        TONE: ${{ inputs.tone }}
        LANGUAGE: ${{ inputs.language }}
      run: node ${{ github.action_path }}/src/index.js
